<?php

namespace zikwall\easyonline\modules\admin\widgets;

use Yii;
use yii\helpers\Url;
use zikwall\easyonline\modules\core\widgets\BaseMenu;

class SettingsMenuTabsWidget extends BaseMenu
{
    public $template = "@zikwall/easyonline/modules/core/widgets/views/tabMenu";

    public function init()
    {
        //$canEditSettings = Yii::$app->user->can(new \zikwall\easyonline\modules\admin\permissions\ManageSettings());

        $this->addItem([
            'label' => Yii::t('AdminModule.widgets_AdminMenuWidget', 'General'),
            'url' => Url::toRoute('/admin/setting/index'),
            'sortOrder' => 100,
            'isActive' => (Yii::$app->controller->module && Yii::$app->controller->module->id == 'admin' && Yii::$app->controller->id == 'setting' && Yii::$app->controller->action->id == 'basic'),
            //'isVisible' => $canEditSettings
        ]);

        $this->addItem([
            'label' => Yii::t('AdminModule.widgets_AdminMenuWidget', 'Appearance'),
            'url' => Url::toRoute('/admin/setting/design'),
            'sortOrder' => 200,
            'isActive' => (Yii::$app->controller->module && Yii::$app->controller->module->id == 'admin' && Yii::$app->controller->id == 'setting' && Yii::$app->controller->action->id == 'design'),
            //'isVisible' => $canEditSettings
        ]);

        parent::init();
    }

    public function run()
    {
        return parent::run(); // TODO: Change the autogenerated stub
    }

}
