<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'the default start page of this community for members' => 'Начальная страница по умолчанию, которую будут видеть участники этого сообщества',
    'the default start page of this community for visitors' => 'Начальная страница по умолчанию, которую будут видеть гости этого сообщества',
    'As owner of this community you can transfer this role to another administrator in community.' => 'Вы, как владелец этого сообщества, можете передать эту роль другому администратору в пространстве.',
    'Community owner' => 'Владелец сообщества',
    'The url contains illegal characters!' => 'URL содержит недопустимые символы!',
    'Transfer ownership' => 'Передать другому владельцу',
    'e.g. example for {baseUrl}/s/example' => 'например, для {baseUrl}/s/example',
];
