<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{displayName} accepted your invite for the community {communityName}' => '{displayName} принял ваше приглашение на вступление в сообщество {communityName}',
    '{displayName} approved your membership for the community {communityName}' => '{displayName} подтвердил ваше участие в пространстве {communityName}',
    '{displayName} declined your invite for the community {communityName}' => '{displayName} отменил ваше приглашение на вступление в сообщество {communityName}',
    '{displayName} declined your membership request for the community {communityName}' => '{displayName} отменил ваш запрос на участие в пространстве {communityName}',
    '{displayName} invited you to the community {communityName}' => '{displayName} пригласил вас в сообщество {communityName}',
    '{displayName} requests membership for the community {communityName}' => '{displayName} отправил запрос на участие в пространстве {communityName}',
];
