<?php

namespace zikwall\easyonline\modules\community\controllers\type;

use Yii;
use yii\web\HttpException;
use zikwall\easyonline\modules\admin\components\Controller;
use zikwall\easyonline\modules\community\models\Community;
use zikwall\easyonline\modules\community\models\Type;
use zikwall\easyonline\modules\community\models\CommunityTypeSearch;
use zikwall\easyonline\modules\community\models\CommunityTypeDelete;

class TypeAdminController extends Controller
{
    public function init()
    {
        $this->subLayout = '@community/views/layouts/main';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchModel = new CommunityTypeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
        ]);
    }

    public function actionEdit()
    {
        $type = Type::findOne(['id' => Yii::$app->request->get('id')]);
        if ($type === null) {
            $type = new Type();
            $type->show_in_directory = 1;
            $type->sort_key = 100;
        }

        if ($type->load(Yii::$app->request->post()) && $type->validate()) {
            $type->save();
            return $this->redirect(['index']);
        }

        return $this->render('edit', [
            'type' => $type,
            'canDelete' => $this->canDeleteCommunityType()
        ]);
    }

    public function actionDelete()
    {
        if (!$this->canDeleteCommunityType()) {
            throw new HttpException(500, 'Could not delete space type!');
        }

        $type = Type::findOne(['id' => Yii::$app->request->get('id')]);
        if ($type === null) {
            throw new \yii\web\HttpException(404, 'Could not find space type!');
        }

        $model = new CommunityTypeDelete();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            foreach (Community::find()->where(['community_type_id' => $type->id])->all() as $space) {
                $space->community_type_id = $model->community_type_id;
                $space->save();
            }
            $type->delete();
            return $this->redirect(['index']);
        }

        $alternativeTypes = \yii\helpers\ArrayHelper::map(Type::find()->where(['!=', 'id', $type->id])->all(), 'id', 'title');

        return $this->render('delete', [
            'type' => $type,
            'model' => $model,
            'alternativeTypes' => $alternativeTypes
        ]);
    }

    private function canDeleteCommunityType()
    {
        return (Type::find()->count() > 1);
    }

}
